version: '3.8'

services:

  nginx:
    build: ./services/nginx
    restart: unless-stopped
    ports:
      - 1337:80
    depends_on:
      - auth
      - feed
      - notification
    
  auth:
    build: ./services/user
    restart: unless-stopped
    # command: gunicorn --bind 0.0.0.0:5020 manage:app # gunicorn
    command: python manage.py run -h 0.0.0.0 -p 5020 # flask
    volumes:
      - ./backend/:/usr/src/app/application
    expose:
      - 5020
    environment:
      - DB_PORT=3307
    env_file:
      - ./services/user/.env.dev
    depends_on:
      - seeder
      - db
  
  feed:
    build: ./services/feed
    restart: unless-stopped
    # command: gunicorn --bind 0.0.0.0:5010 manage:app # gunicorn
    command: python manage.py run -h 0.0.0.0 -p 5010 # flask
    volumes:
      - ./backend/:/usr/src/app/application
    expose:
      - 5010
    environment:
      - DB_PORT=3307
    env_file:
      - ./services/feed/.env.dev
    depends_on:
      - seeder
      - db
      - auth
  
  notification:
    build: ./services/notification
    # command: gunicorn --bind 0.0.0.0:5030 --worker-class eventlet -w 1 manage:app # gunicorn
    restart: unless-stopped
    command: python manage.py # flask_socketio
    volumes:
      - ./backend/:/usr/src/app/application
    expose:
      - 5030
    env_file:
      - ./services/notification/.env.dev
    depends_on:
      - seeder
      - auth
      - redis
  
  seeder:
    build: ./services/database-manager
    command: python manage.py seed_db
    volumes:
      - ./backend/:/usr/src/app/application
    environment:
      - DB_PORT=3307
    env_file:
      - ./services/database-manager/.env.dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  redis:
    image: redis:latest
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - ./cachedata:/root/redis
      # - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf
    # command: --requirepass $${REDIS_PASSWORD}
    env_file:
      - ./services/redis/.env.dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 10
      interval: 5s
  
  db:
    image: mysql:8
    restart: unless-stopped
    expose:
      - 3307
    ports:
      - 3308:3307
    environment:
      - MYSQL_TCP_PORT=3307
    env_file:
      - ./services/mysql/.env.dev
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s
    volumes:
      - ./dbdata:/var/lib/mysql/
